#!/bin/bash

die() {
  echo >&2 $1
  exit 1
}

usage() {
  echo -e >&2 "Usage: $0 deb output"
  exit 2
}

extract() {
    local deb=$1
    local out=$2
    if [ ! -d "$out" ]; then
        mkdir $out
    fi
    local tmp=`mktemp -d`
    cp $deb $tmp/pkg.deb
    pushd $tmp 1>/dev/null
    ar x pkg.deb || die "ar failed"
    tar xf data.tar.* || die "tar failed"
    popd 1>/dev/null
    
    cp $tmp/lib/*/* $out 2>/dev/null || cp $tmp/lib32/* $out 2>/dev/null \
      || cp $tmp/usr/lib/debug/lib/*/* $out 2>/dev/null || cp $tmp/usr/lib/debug/lib32/* $out 2>/dev/null \
      || die "Failed to save. Check it manually $tmp"
    
    rm -rf $tmp
}

if [[ $# -ne 2 ]]; then
    usage
fi

extract "$1" "$2"


